version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:00'
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    groups:
      production-patches:
        dependency-type: production
        update-types:
          - patch
      development-patches:
        dependency-type: development
        update-types:
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '04:30'
      timezone: Etc/UTC
    open-pull-requests-limit: 10
